name:                my-game
version:             0.1.0.0
github:              "githubuser/my-game"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- data/configs/*.json
- assets/*.png

data-files:
- data/configs/game.json
- assets/outside.png
- assets/main_character_sheet.png

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/my-game#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6.2
- sdl2 >= 2.0.6
- sdl2-image >= 2.1.0.0
- text
- mtl >= 2.2.2
- random >= 1.2.1
- containers >= 0.6.4.1
- aeson >= 2.0.3.0
- directory >= 1.3.6.0

library:
  source-dirs: src

executables:
  my-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-game

tests:
  my-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-game
